server:
  port: 8888
  shutdown: graceful
  compression:
    enabled: true
---
spring:
  application:
    name: exchange-service
---
spring:
  profiles:
    include:
      - consul
---
# Api documentation configuration
springdoc:
  swagger-ui:
    path: /swagger
    display-request-duration: true
    default-models-expand-depth: -1
    default-model-expand-depth: 100
  api-docs:
    path: /v3/api-docs
  open-api:
    servers[0]:
      url: http://localhost:8000/exchange
      description: Gateway
    servers[1]:
      url: http://localhost:8888
      description: Exchange Service
---
spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://root:root@localhost:27017/exchange?authSource=admin
---
# Kafka base configuration
spring:
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.cloudevents.kafka.CloudEventSerializer
      batch-size: 200000
      compression-type: lz4
      acks: 1
      properties:
        linger.ms: 100
        spring.json.add.type.headers: false
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.cloudevents.kafka.CloudEventDeserializer
      isolation-level: read_committed
      properties:
        spring.json.trusted.packages: '*'
        spring.json.use.type.headers: false
    admin:
      auto-create: true
---
# Kafka in-out topic to another microservice
kafka:
  order-book:
    request-topic: order-book-request
    reply-topic: order-book-reply
    partition-count: 1
    replication-factor: 1
    consumer:
      group-id: exchange-service
