---
# See: org/springframework/boot/autoconfigure/kafka/KafkaProperties.java
spring:
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.cloudevents.kafka.CloudEventSerializer
      properties:
        'linger.ms': 500
        spring.json.add.type.headers: false

---
order-book:
  topic: order-book-request
  reply-topic: order-book-reply
  consume-poll-size: 10000
  consume-poll-duration: 100
