---
spring.application.name: orderbook-business-processor
server:
  port: 8085
---
spring:
  profiles:
    include:
      - kafka
      - database
      - tracing
---
schedule:
  sync-database-interval: 500
