---
spring.application.name: orderbook-business-processor
server:
  port: 8085
  shutdown: graceful
---
spring:
  profiles:
    include:
      - kafka
      - database
---
schedule:
  sync-database-interval: 500
