server.port: 8000
---
spring:
  application:
    name: api-gateway
---
spring:
  profiles:
    include:
      - swagger
      - tracing
---
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            maxAge: 3600
---
spring:
  cloud:
    gateway:
      routes:
        - id: auth-api
          uri: http://localhost:8800
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
        - id: exchange-api
          uri: http://localhost:8888
          predicates:
            - Path=/exchange/**
          filters:
            - RewritePath=/exchange/(?<segment>.*), /$\{segment}
